### PR TITLE
Added boAt Product Card

### PR DESCRIPTION
**Pull request by AmitSahoo45**
Added boAt product card made using HTML, CSS, JavaScript

### CODE REVIEW

**Comment by jay-2000** [comment]
> Added boAt product card made using HTML, CSS, JavaScript

hey @AmitSahoo45 can you just create the issue first with the name of your project so that i can assign you the issue first and add the tag of hacktoberfest than you can open your PR and I'll review it and merge it and don't forget to pull / fetch the previous changes and also add screenshot of yorr project in PR Comment

**Comment by jay-2000** [comment]
> > Added boAt product card made using HTML, CSS, JavaScript
> 
> hey @AmitSahoo45 can you just create the issue first with the name of your project so that i can assign you the issue first and add the tag of hacktoberfest than you can open your PR and I'll review it and merge it and don't forget to pull / fetch the previous changes and also add screenshot of yorr project in PR Comment

hey @AmitSahoo45 can you just sync fork your branch since your branch is 37 commits behind

**Comment by AmitSahoo45** [comment]
Done

**Comment by jay-2000** [comment]
> Done

hey @AmitSahoo45 can you sync fork since you are 55 commits behind
image

**Pull request closed without merging**
