### PR TITLE
A street dog charity site added

### PR DESCRIPTION
**Pull request by ritam077**

### CODE REVIEW

**Comment by jay-2000** [comment]
> _ No description provided. _

hey @ritam077 can you just create the issue first with the name of your project so that i can assign you the issue first and add the tag of hacktoberfest than you can open your PR and I'll review it and merge it and don't forget to pull / fetch the previous changes and also add screenshot of your project in PR Comment

**Comment by ritam077** [comment]
Besically It is a frontend site with demo donation button for Street Dog Charity Donation site,,,,,,,

**Comment by ritam077** [comment]
Screenshot (61)

**Comment by jay-2000** [comment]
> Besically It is a frontend site with demo donation button for Street Dog Charity Donation site,,,,,,,

yeah but you still need to make an issue for with the same name so that i can assign you with the tag of hacktoberfest

**Comment by ritam077** [comment]
#38 donation button added

**Comment by jay-2000** [comment]
@ritam077 
image
 since you branche is 3 commit behind press ths sync fork and update first and then i can merge your PR

**Comment by ritam077** [comment]
Done sir

**Comment by jay-2000** [comment]
> Done sir

@ritam077  Brother its  still showing do it one more time

**Comment by ritam077** [comment]
Screenshot (63)
Done

**Review by jay-2000 — APPROVED** [review]
great work good effort
keep contributing

**Pull request merged**
