### PR TITLE
Added TIC-TAC-TOE game on JavaScript.

### LINKED ISSUE #45: Tic-tac-toe JavaScript game

### PR DESCRIPTION
**Pull request by prabhat7k**
resolved #45

### CODE REVIEW

**Comment by jay-2000** [comment]
> resolved #45

hey @prabhat7k can you add the screenshots here so that i can review

**Comment by prabhat7k** [comment]
image
accepting the vs computer alert will let us play in 1 player mode(vs computer).
or else it will run in two player mode. 
image
by clicking on the boxes it will allow us to play the move.
image
in the end the winner gets displayed.

**Review by jay-2000 — APPROVED** [review]
Great work Keep contributing

Don't forget to star our repository

**Comment by prabhat7k** [comment]
> Great work Keep contributing
> 
> Don't forget to star our repository

yup sure!!

**Pull request merged**
