### PR TITLE
DrumKit 

### PR DESCRIPTION
**Pull request by PumpkinManiac**

### CODE REVIEW

**Comment by jay-2000** [comment]
Can you provide me the screen shot of how it looks like @PumpkinManiac

**Comment by jay-2000** [comment]
> Can you provide me the screen shot of how it looks like @PumpkinManiac

So that i can merge your PR

**Comment by PumpkinManiac** [comment]
image

Sure!!

**Comment by jay-2000** [comment]
> image
> 
> Sure!!

Looks cool @PumpkinManiac 
Happy open source

**Pull request merged**
