### PR TITLE
 2_Player_DiceGame.html

### PR DESCRIPTION
**Pull request by kunal15112001**

### CODE REVIEW

**Comment by jay-2000** [comment]
> _ No description provided. _

hey @kunal15112001 can you just create the issue first with the name of your project so that i can assign you the issue first and add the tag of hacktoberfest than you can open your PR and I'll review it and merge it and don't forget to pull / fetch the previous changes and also add screenshot of yorr project in PR Comment

**Comment by kunal15112001** [comment]
Sure

**Comment by kunal15112001** [comment]
img1
img2

**Review by jay-2000 — COMMENTED** [review]
great work
keep contributing 
star our repository

**Comment by kunal15112001** [comment]
if I contribute in same repository then will it count as other individual contribution in Hackoberfest or not?

**Pull request merged**
