### PR TITLE
feat: Add Stock Management Project files

### LINKED ISSUE #56: feat: Stock Management System [Java, Java Swing]
Please assign this issue to me and add the relevant labels.
This is a full-fledged project.

### PR DESCRIPTION
**Pull request by RoshanMhatre**
Fix #56 

v1

v2

### CODE REVIEW

**Comment by RoshanMhatre** [comment]
Please review the PR and add the relevant labels.

**Comment by jay-2000** [comment]
> Please review the PR and add the relevant labels. All the images of the project are present in the SMSImages folder.

try to make only web based project so that in case some one wants to enhance your part i can assign it to that per son as well and most imp. sync fork the repository before opening the new PR

**Comment by RoshanMhatre** [comment]
So this PR won't be able to merge @jay-2000?

**Comment by jay-2000** [comment]
> So this PR won't be able to merge @jay-2000?

before merging you have just press the sync fork from the branch through which you are committing and pushing the code

**Comment by jay-2000** [comment]
> So this PR won't be able to merge @jay-2000? This is a desktop application which we can run using xampp server.

yeah i can understand  but next time onwards just for this repository open PR for only web and nor  desktop

**Comment by jay-2000** [comment]
> > So this PR won't be able to merge @jay-2000? This is a desktop application which we can run using xampp server.
> 
> yeah i can understand but next time onwards just for this repository open PR for only web and nor desktop

just sync fork it since your branch is lagging behind few commits so that i can merge it

**Comment by RoshanMhatre** [comment]
Alright @jay-2000.
Actually, my branch is in sync with this repo.
 
v3

**Comment by RoshanMhatre** [comment]
Also, you might be able to see on this page, it shows 'This branch has no conflicts with the base branch'. I think, you can successfully merge it without any issue as such.

**Comment by RoshanMhatre** [comment]
Please check now @jay-2000

**Pull request merged**
