### PR TITLE
Added quizapp folder

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
Hey 👋, @jay-2000 

I have added new folder named `VK_QuizApp`which has quiz website made of HTML, CSS, JS.

Please review my code and let me know if any changes needed.
Please add `hacktoberfest-accepted`, so that I can keep track of all my contributions this month

**Screenshots:**:

Homepage
image

quiz page
image

**Issue:** #37 

Appreciate that!

### CODE REVIEW

**Comment by jay-2000** [comment]
> Hey 👋, @jay-2000
> 
> I have added new folder named `VK_QuizApp`which has quiz website made of HTML, CSS, JS.
> 
> Please review my code and let me know if any changes needed. Please add `hacktoberfest-accepted`, so that I can keep track of all my contributions this month
> 
> Appreciate that!

hey @jsvigneshkanna can you just share the screenshot in comment so that i can review it

**Comment by jsvigneshkanna** [comment]
I have adde screenshots in PR itself, just now edited the message

**Comment by jsvigneshkanna** [comment]
Issue: #37

**Comment by jay-2000** [comment]
> I have adde screenshots in PR itself, just now edited the message

image

your branch is 3 commit behind so fix that

**Comment by jay-2000** [comment]
> > I have adde screenshots in PR itself, just now edited the message
> 
> image
> 
> your branch is 3 commit behind so fix that by pressing the sync fork and then update

if you don't know what sync fork is check this out 
image

**Comment by jay-2000** [comment]
@jsvigneshkanna any problem?

**Comment by jsvigneshkanna** [comment]
@jay-2000 , can you please check now, I have updated the commits

**Comment by jay-2000** [comment]
> @jay-2000 , can you please check now, I have updated the commits

its still show 6 commits behind can you sync for again @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@jay-2000 ,

image

Did the same update to new branch

**Review by jay-2000 — APPROVED** [review]
great work
keep contributing
star our repo

**Pull request merged**
