### PR TITLE
embark-CollegeJourney

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
Project video:  https://www.loom.com/share/eb4c05ce5820487b8bd525a4cea6d09c

Some snipets:
image
image
image

### CODE REVIEW

**Comment by Nitya-Pasrija** [comment]
@jay-2000 
Would appreciate if you were to merge this :)

**Comment by jay-2000** [comment]
> Project video: https://www.loom.com/share/eb4c05ce5820487b8bd525a4cea6d09c
> 
> Some snipets: image image image

hey @Nitya-Pasrija can you just create the issue first with the name of your project so that i can assign you the issue first and add the tag of hacktoberfest than you can open your PR and I'll review it and merge it and don't forget to pull / fetch the previous changes using sync fork and also add screenshot of your project in PR Comment

**Comment by Nitya-Pasrija** [comment]
Sure, no worries

**Comment by jay-2000** [comment]
> Sure, no worries

don't forget to sync fork the branch

**Pull request merged**
